# Generated by Django 4.0.4 on 2022-06-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_category_description'),
        ('userApp', '0003_performance_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='cat',
            field=models.ForeignKey(default='cat', on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category'),
        ),
    ]
