# Generated by Django 4.0.4 on 2022-06-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_alter_performance_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='cat',
        ),
    ]
