# Generated by Django 4.0.4 on 2022-06-19 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_category_description'),
        ('userApp', '0007_remove_performance_cat_performance_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.CharField(max_length=2)),
                ('total', models.CharField(max_length=2)),
                ('per', models.CharField(max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.userinfo')),
            ],
            options={
                'db_table': 'Performances',
            },
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
