# Generated by Django 4.0.4 on 2022-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_performances_delete_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performances',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
