# Generated by Django 4.0.4 on 2022-06-19 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0009_alter_performances_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('correct', models.CharField(max_length=2)),
                ('total', models.CharField(max_length=2)),
                ('per', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.userinfo')),
            ],
            options={
                'db_table': 'Performance',
            },
        ),
        migrations.DeleteModel(
            name='Performances',
        ),
    ]
