# Generated by Django 4.0.4 on 2022-06-19 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_category_description'),
        ('userApp', '0010_performance_delete_performances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userApp.userinfo'),
        ),
    ]
