# Generated by Django 4.0.4 on 2022-06-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_category_description'),
        ('userApp', '0011_alter_performance_category_alter_performance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.userinfo'),
        ),
    ]
