# Generated by Django 4.0.4 on 2022-06-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0012_alter_performance_category_alter_performance_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
