# Generated by Django 4.0.4 on 2022-06-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0014_performance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
