# Generated by Django 4.0.4 on 2022-06-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default="The language for building web pages", max_length=100),
        ),
    ]
